apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongo_root_username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongo_root_password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongo-db-configmap
              key: database_url

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  # to connect to a Pod through label
  selector:
    app: mongo-express
  type: LoadBalancer # Accept external requests
  ports:
  - port: 8081 # service port
    targetPort: 8081 # containerPort of deployment
    #nodePort: 30200  # port where's the external ip address will be open between 30000-32767
    # if you don't declare it, k8s will assign a random port for you
