apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-secret
type: Opaque
# The values here must to be base64 encoded
# echo -n 'mongo_db_user' | base64
# echo -n 'mongo_db_password' | base64
data:
  mongo_root_username: bW9uZ29fZGJfdXNlcg==
  mongo_root_password: bW9uZ29fZGJfcGFzc3dvcmQ=
