apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress-controller
  labels:
    app: nginx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-ingress-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-ingress-controller
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80 # this port needs to match the containerPort

---

# to make it working you'll need to install this
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.41.2/deploy/static/provider/cloud/deploy.yaml
# the command will enable the nginx-ingress locally using your wsl2 environment

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: nginx-ingress-controller
spec:
  defaultBackend:
    service:
      name: nginx-service
      port:
        number: 8080
  rules:
  - host: nginx-ingress.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 8080
