apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-reverse-proxy
  labels:
    app: nginx-replicaset-environment
spec:
  replicas: 4
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: nginx
      labels:
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx:1.19